version: "3"
services:
  kronos:
    build:
      context: .
      dockerfile: Dockerfile
    image: kronos:latest
    network_mode: bridge
    entrypoint:
      - /bin/entrypoint.sh
    environment:
      AWS_S3_ACCESS_KEY_ID: "${AWS_S3_ACCESS_KEY_ID}"
      AWS_S3_SECRET_ACCESS_KEY: "${AWS_S3_SECRET_ACCESS_KEY}"
      KRONOS_SCORING_REGION: "${KRONOS_SCORING_REGION}"  # [ECOSYSTEM] - <maven/pypi/npm>
      DEPLOYMENT_PREFIX: "${DEPLOYMENT_PREFIX}"  # <DEV/STAGE/PROD> - affects where the data and log for training gets stored.
      SERVICE_PORT: "6006"
      SERVICE_TIMEOUT: "900"
      SPARK_HOME: "/usr/local/spark"
      PY4J_VERSION: "py4j-0.10.4-src.zip"
      GREMLIN_REST_URL: "http://bayesian-gremlin-http-preview-b6ff-bayesian-preview.b6ff.rh-idev.openshiftapps.com"  # <url>:<port>
      FLASK_LOGGING_LEVEL: "DEBUG"
    ports:
        - "6006:6006"
